openapi: 3.0.0
info:
  title: Isaac Sim Integration API
  description: API for interacting with Isaac Sim simulations and retrieving simulation data
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/simulations:
    get:
      summary: List available simulations
      description: Retrieve a list of available Isaac Sim simulation environments
      responses:
        '200':
          description: List of available simulations
          content:
            application/json:
              schema:
                type: object
                properties:
                  simulations:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: Unique identifier for the simulation
                        name:
                          type: string
                          description: Display name of the simulation
                        description:
                          type: string
                          description: Brief description of the simulation
                        thumbnail_url:
                          type: string
                          description: URL to thumbnail image of the simulation

  /api/simulations/{simulationId}/run:
    post:
      summary: Run a simulation
      description: Start running a specific Isaac Sim simulation
      parameters:
        - name: simulationId
          in: path
          required: true
          schema:
            type: string
          description: ID of the simulation to run
      responses:
        '200':
          description: Simulation started successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [started, running, error]
                  simulation_id:
                    type: string
                  message:
                    type: string

  /api/simulations/{simulationId}/data:
    get:
      summary: Get simulation data
      description: Retrieve data generated by a running Isaac Sim simulation
      parameters:
        - name: simulationId
          in: path
          required: true
          schema:
            type: string
          description: ID of the simulation
      responses:
        '200':
          description: Simulation data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  sensor_data:
                    type: object
                    description: Data from various sensors in the simulation
                  robot_state:
                    type: object
                    description: Current state of the robot in the simulation
                  environment_data:
                    type: object
                    description: Information about the simulation environment

  /api/ros/nodes:
    get:
      summary: List ROS nodes
      description: Retrieve a list of active ROS nodes in the Isaac ROS ecosystem
      responses:
        '200':
          description: List of active ROS nodes
          content:
            application/json:
              schema:
                type: object
                properties:
                  nodes:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          description: Name of the ROS node
                        type:
                          type: string
                          description: Type or purpose of the node
                        status:
                          type: string
                          enum: [active, inactive, error]
                        connections:
                          type: object
                          description: Information about topic connections